export const rooms = [
	{ id: '1', name: 'Kiddie', image: 'https://i.pravatar.cc/200?img=1', unread: 1, last: 'Shangri-la is not the inner man of the ego.' },
	{ id: '2', name: 'Fred', image: 'https://i.pravatar.cc/200?img=2', unread: 0, last: 'The unexplainable is the ground of your own reality. Our new volume for justice is to trap others theosophically.' },
	{ id: '3', name: 'Sasha Imtabel', image: 'https://i.pravatar.cc/200?img=3', unread: 3, last: 'The key to joy is to see clearly.' },
	{ id: '5', name: 'Patrisia', image: 'https://i.pravatar.cc/200?img=5', unread: 0, last: 'Manifestation doesn’t compassionately yearn any lama — but the teacher is what preaches..' },
	{ id: 'public', name: 'SafeSpace', image: 'https://picsum.photos/200/200', unread: 0, last: 'Manifestation doesn’t compassionately yearn any lama — but the teacher is what preaches..' },
	{ id: '11', name: 'Kiddie', image: 'https://i.pravatar.cc/200?img=1', unread: 1, last: 'Shangri-la is not the inner man of the ego.' },
	{ id: '22', name: 'Fred', image: 'https://i.pravatar.cc/200?img=2', unread: 0, last: 'The unexplainable is the ground of your own reality. Our new volume for justice is to trap others theosophically.' },
	{ id: '33', name: 'Sasha Imtabel', image: 'https://i.pravatar.cc/200?img=3', unread: 3, last: 'The key to joy is to see clearly.' },
	{ id: '54', name: 'Patrisia', image: 'https://i.pravatar.cc/200?img=5', unread: 0, last: 'Manifestation doesn’t compassionately yearn any lama — but the teacher is what preaches..' },
	{ id: '55', name: 'Felix', image: 'https://picsum.photos/200/200', unread: 0, last: 'Manifestation doesn’t compassionately yearn any lama — but the teacher is what preaches..' },
	{ id: '16', name: 'Kiddie', image: 'https://i.pravatar.cc/200?img=1', unread: 1, last: 'Shangri-la is not the inner man of the ego.' },
	{ id: '27', name: 'Fred', image: 'https://i.pravatar.cc/200?img=2', unread: 0, last: 'The unexplainable is the ground of your own reality. Our new volume for justice is to trap others theosophically.' },
	{ id: '38', name: 'Sasha Imtabel', image: 'https://i.pravatar.cc/200?img=3', unread: 3, last: 'The key to joy is to see clearly.' },
	{ id: '59', name: 'Patrisia', image: 'https://i.pravatar.cc/200?img=5', unread: 0, last: 'Manifestation doesn’t compassionately yearn any lama — but the teacher is what preaches..' },
	{ id: '88', name: 'kkk', image: 'https://picsum.photos/200/200', unread: 0, last: 'Manifestation doesn’t compassionately yearn any lama — but the teacher is what preaches..' },
	{ id: '13', name: 'Kiddie', image: 'https://i.pravatar.cc/200?img=1', unread: 1, last: 'Shangri-la is not the inner man of the ego.' },
	{ id: '24', name: 'Fred', image: 'https://i.pravatar.cc/200?img=2', unread: 0, last: 'The unexplainable is the ground of your own reality. Our new volume for justice is to trap others theosophically.' },
	{ id: '35', name: 'Sasha Imtabel', image: 'https://i.pravatar.cc/200?img=3', unread: 3, last: 'The key to joy is to see clearly.' },
	{ id: '56', name: 'Scila', image: 'https://i.pravatar.cc/200?img=5', unread: 0, last: 'Manifestation doesn’t compassionately yearn any lama — but the teacher is what preaches..' },
	{ id: '31', name: 'Nasty', image: 'https://picsum.photos/200/200', unread: 0, last: 'Manifestation doesn’t compassionately yearn any lama — but the teacher is what preaches..' },
]
