export const rooms = [
	{ uid: '1', name: 'Kiddie', image: 'https://i.pravatar.cc/200?img=1', unread: 1, last: 'Shangri-la is not the inner man of the ego.' },
	{ uid: '2', name: 'Fred', image: 'https://i.pravatar.cc/200?img=2', unread: 0, last: 'The unexplainable is the ground of your own reality. Our new volume for justice is to trap others theosophically.' },
	{ uid: '3', name: 'Sasha Imtabel', image: 'https://i.pravatar.cc/200?img=3', unread: 3, last: 'The key to joy is to see clearly.' },
	{ uid: '5', name: 'Patrisia', image: 'https://i.pravatar.cc/200?img=5', unread: 0, last: 'Manifestation doesn’t compassionately yearn any lama — but the teacher is what preaches..' },
	{ uid: 'public', name: 'SafeSpace', image: 'https://picsum.photos/200/200', unread: 0, last: 'Manifestation doesn’t compassionately yearn any lama — but the teacher is what preaches..' },
	{ uid: '11', name: 'Kiddie', image: 'https://i.pravatar.cc/200?img=1', unread: 1, last: 'Shangri-la is not the inner man of the ego.' },
	{ uid: '22', name: 'Fred', image: 'https://i.pravatar.cc/200?img=2', unread: 0, last: 'The unexplainable is the ground of your own reality. Our new volume for justice is to trap others theosophically.' },
	{ uid: '33', name: 'Sasha Imtabel', image: 'https://i.pravatar.cc/200?img=3', unread: 3, last: 'The key to joy is to see clearly.' },
	{ uid: '54', name: 'Patrisia', image: 'https://i.pravatar.cc/200?img=5', unread: 0, last: 'Manifestation doesn’t compassionately yearn any lama — but the teacher is what preaches..' },
	{ uid: '55', name: 'Felix', image: 'https://picsum.photos/200/200', unread: 0, last: 'Manifestation doesn’t compassionately yearn any lama — but the teacher is what preaches..' },
	{ uid: '16', name: 'Kiddie', image: 'https://i.pravatar.cc/200?img=1', unread: 1, last: 'Shangri-la is not the inner man of the ego.' },
	{ uid: '27', name: 'Fred', image: 'https://i.pravatar.cc/200?img=2', unread: 0, last: 'The unexplainable is the ground of your own reality. Our new volume for justice is to trap others theosophically.' },
	{ uid: '38', name: 'Sasha Imtabel', image: 'https://i.pravatar.cc/200?img=3', unread: 3, last: 'The key to joy is to see clearly.' },
	{ uid: '59', name: 'Patrisia', image: 'https://i.pravatar.cc/200?img=5', unread: 0, last: 'Manifestation doesn’t compassionately yearn any lama — but the teacher is what preaches..' },
	{ uid: '88', name: 'kkk', image: 'https://picsum.photos/200/200', unread: 0, last: 'Manifestation doesn’t compassionately yearn any lama — but the teacher is what preaches..' },
	{ uid: '13', name: 'Kiddie', image: 'https://i.pravatar.cc/200?img=1', unread: 1, last: 'Shangri-la is not the inner man of the ego.' },
	{ uid: '24', name: 'Fred', image: 'https://i.pravatar.cc/200?img=2', unread: 0, last: 'The unexplainable is the ground of your own reality. Our new volume for justice is to trap others theosophically.' },
	{ uid: '35', name: 'Sasha Imtabel', image: 'https://i.pravatar.cc/200?img=3', unread: 3, last: 'The key to joy is to see clearly.' },
	{ uid: '56', name: 'Scila', image: 'https://i.pravatar.cc/200?img=5', unread: 0, last: 'Manifestation doesn’t compassionately yearn any lama — but the teacher is what preaches..' },
	{ uid: '31', name: 'Nasty', image: 'https://picsum.photos/200/200', unread: 0, last: 'Manifestation doesn’t compassionately yearn any lama — but the teacher is what preaches..' },
]
