env:
  browser: true
  es2021: true
  amd: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
  - simple-import-sort
  - import
#  - react-pug
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
#  - plugin:react-pug/all
rules:
  indent:
    - error
    - tab
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  object-property-newline:
    - error
    - allowAllPropertiesOnSameLine: true
  object-curly-spacing:
    - error
    - always
  comma-spacing:
    - error
    - before: false
      after: true
  react/react-in-jsx-scope: off
  react/no-unknown-property: off
  "@typescript-eslint/no-empty-interface": off
  simple-import-sort/exports: error
  quote-props:
    - error
    - as-needed
  react/jsx-max-props-per-line:
    - 1
    - maximum:
        single: 3
        multi: 1
  react/jsx-first-prop-new-line:
    - 1
    - multiline
  react/jsx-closing-bracket-location: 1
  react/jsx-wrap-multilines: 1
  react/jsx-no-literals:
    - error
  "@typescript-eslint/no-unused-vars":
    - error
    - varsIgnorePattern: "^_"
      args: after-used
  import/newline-after-import:
    - error
    - count: 2
  eol-last:
    - error
    - always
  simple-import-sort/imports:
    - error
    - groups:
        - - "^preact"
          - "^@?\\w"
        - - "^@mui"
        - - "^@mui/icons-material"
        - - "^@/services"
        - - "^@/model"
        - - "^@/ui"
        - - "^@/components"
  no-multiple-empty-lines: error
  react/prop-types: off
