---
env:
  browser: true
  es2021: true
  amd: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
plugins:
  - react
  - "@typescript-eslint"
  - simple-import-sort
  - import
settings: {}
overrides:
  - files:
      - "*.astro"
    parser: astro-eslint-parser
    parserOptions:
      parser: "@typescript-eslint/parser"
      extraFileExtensions:
        - ".astro"
    rules:
      react/jsx-key: 'off'
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  object-property-newline:
    - error
    - allowAllPropertiesOnSameLine: true
  object-curly-spacing:
    - error
    - always
  comma-spacing:
    - error
    - before: false
      after: true
  react/react-in-jsx-scope: 'off'
  react/no-unknown-property: 'off'
  no-multiple-empty-lines: error
  "@typescript-eslint/no-empty-interface": 'off'
  simple-import-sort/exports: error
  quote-props:
    - error
    - as-needed
  react/jsx-max-props-per-line:
    - 1
    - maximum:
        single: 3
        multi: 1
  react/jsx-first-prop-new-line:
    - 1
    - multiline
  react/jsx-closing-bracket-location: 1
  react/jsx-wrap-multilines: 1
  "@typescript-eslint/no-unused-vars":
    - error
    - varsIgnorePattern: "^_"
      args: after-used
  unicorn/filename-case: 'off'
  unicorn/prevent-abbreviations: 'off'
  unicorn/prefer-spread: 'off'
  unicorn/no-null: 'off'
  unicorn/no-negated-condition: 'off'
  import/newline-after-import:
    - error
    - count: 2
  eol-last:
    - error
    - always
  simple-import-sort/imports:
    - error
    - groups:
        - - "^react"
          - "^@?\\w"
        - - "^@mui"
        - - "^@/services"
        - - "^@/ui"
        - - "^@/components"
