packages:
  - name: auth
    environment:
      DB_CONNECTION_STRING: "${AUTH_CONNECTION_STRING}"
    functions:
      - name: send
        runtime: nodejs:18
        web: true
      - name: verify
        runtime: nodejs:18
        web: true
        environment:
          JWT_SECRET: "${JWT_SECRET}"
  - name: profiles
    environment:
      DB_CONNECTION_STRING: "${KEENQ_CONNECTION_STRING}"
    functions:
      - name: send
        runtime: nodejs:18
        web: true
