packages:
  - name: auth
    environment:
      DB_CONNECTION_STRING: "${DB_CONNECTION_STRING}"
    functions:
      - name: send
        runtime: nodejs:18
        web: true
      - name: verify
        runtime: nodejs:18
        web: true
        environment:
          JWT_SECRET: "${JWT_SECRET}"
  - name: location
    environment:
      DB_CONNECTION_STRING: "${DB_CONNECTION_STRING}"
      GOOGLE_MAPS_API_KEY: "${GOOGLE_MAPS_API_KEY}"
    functions:
      - name: cities
        runtime: nodejs:18
        web: true
  - name: members
    environment:
      DB_CONNECTION_STRING: "${DB_CONNECTION_STRING}"
    functions:
      - name: match
        runtime: nodejs:18
        web: true
      - name: matched
        runtime: nodejs:18
        web: true
      - name: lang
        runtime: nodejs:18
        web: true

