packages:
  - name: auth
    environment:
      DB_CONNECTION_STRING: "${DB_CONNECTION_STRING}"
      TWILIO_ACCOUNT_SID: "${TWILIO_ACCOUNT_SID}"
      TWILIO_AUTH_TOKEN: "${TWILIO_AUTH_TOKEN}"
    functions:
      - name: send
        runtime: nodejs:18
        web: true
      - name: verify
        runtime: nodejs:18
        web: true
        environment:
          JWT_SECRET: "${JWT_SECRET}"
  - name: location
    environment:
      DB_CONNECTION_STRING: "${DB_CONNECTION_STRING}"
      GOOGLE_MAPS_API_KEY: "${GOOGLE_MAPS_API_KEY}"
    functions:
      - name: cities
        runtime: nodejs:18
        web: true
  - name: match
    environment:
      DB_CONNECTION_STRING: "${DB_CONNECTION_STRING}"
    functions:
      - name: match
        runtime: nodejs:18
        web: true
      - name: matched
        runtime: nodejs:18
        web: true
  - name: members
    functions:
      - name: lang
        runtime: nodejs:18
        web: true
  - name: rooms
    environment:
      DB_CONNECTION_STRING: "${DB_CONNECTION_STRING}"
    functions:
      - name: create
        runtime: nodejs:18
        web: true
  - name: utils
    environment:
      DB_CONNECTION_STRING: "${DB_CONNECTION_STRING}"
    functions:
      - name: id
        runtime: nodejs:18
        web: true
  - name: push
    environment:
      DB_CONNECTION_STRING: "${DB_CONNECTION_STRING}"
      VAPID_PUBLIC_KEY: "${VAPID_PUBLIC_KEY}"
      VAPID_PRIVATE_KEY: "${VAPID_PRIVATE_KEY}"
    functions:
      - name: test
        runtime: nodejs:18
        web: true
      - name: msg
        runtime: nodejs:18
        web: true
