packages:
  - name: auth
    environment:
      PG_CONNECTION_STRING: "${PG_CONNECTION_STRING}"
    functions:
      - name: send
        runtime: nodejs:18
        web: true
      - name: verify
        runtime: nodejs:18
        web: true
        environment:
          JWT_SECRET: "${JWT_SECRET}"
