packages:
  - name: auth
    runtime: nodejs:18
    environment:
      DB_CONNECTION_STRING: "${AUTH_CONNECTION_STRING}"
    functions:
      - name: send
        web: true
      - name: verify
        web: true
        environment:
          JWT_SECRET: "${JWT_SECRET}"
  - name: profiles
    runtime: nodejs:18
    environment:
      DB_CONNECTION_STRING: "${KEENQ_CONNECTION_STRING}"
    functions:
      - name: create
        web: true
